name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install gunicorn

    - name: Run Flask App
      run: |
        gunicorn -w 4 -b 0.0.0.0:5000 app:app

    - name: Check if Flask App is running
      run: |
        sleep 5 # Wait for the server to start
        if curl -sSf http://localhost:5000; then
          echo "Flask application is running."
        else
          echo "Failed to start the application"
          exit 1
        fi
  cleanup:
      runs-on: ubuntu-latest
      needs: [build]
  
      steps:
      - name: Stop Gunicorn
        run: |
          PID=$(pgrep gunicorn)
          if [ -n "$PID" ]; then
            kill "$PID"
            echo "Gunicorn process stopped."
          else
            echo "No Gunicorn process running."
          fi
